In [9]:
import zipfile
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from scipy import stats

In [ ]:
zip_path = "cranberry-data.zip"
extract_to = "cranberry_data" 

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_to)

print("Unzipped successfully!")

Unzipped successfully!

In [3]:
path = r"cranberry_data\cranberry-data\data_mixed\Phenolics_RawData.xlsx"
df = pd.read_excel(path, engine="openpyxl")
df.head()

,Date,Sample ID,Tube#,Rep1 Absorbance 765 nm,Rep2 Absorbance 765 nm,Rep3 Absorbance 765 nm
0,2025-01-06,Std0,0,0.023,0.020,0.006
1,2025-01-06,Std50,50,0.066,0.064,0.061
2,2025-01-06,std100,100,0.109,0.119,0.116
3,2025-01-06,std150,150,0.177,0.194,0.176
4,2025-01-06,std250,250,0.271,0.292,0.308

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Date                    128 non-null    datetime64[ns]
 1   Sample ID               128 non-null    object
 2   Tube#                   128 non-null    int64
 3   Rep1 Absorbance 765 nm  128 non-null    float64
 4   Rep2 Absorbance 765 nm  128 non-null    float64
 5   Rep3 Absorbance 765 nm  128 non-null    float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(1)
memory usage: 6.1+ KB

In [5]:
df

,Date,Sample ID,Tube#,Rep1 Absorbance 765 nm,Rep2 Absorbance 765 nm,Rep3 Absorbance 765 nm
0,2025-01-06,Std0,0,0.023,0.020,0.006
1,2025-01-06,Std50,50,0.066,0.064,0.061
2,2025-01-06,std100,100,0.109,0.119,0.116
3,2025-01-06,std150,150,0.177,0.194,0.176
4,2025-01-06,std250,250,0.271,0.292,0.308
...,...,...,...,...,...,...
123,2025-01-16,std750,750,0.793,0.780,0.802
124,2025-01-16,MQB3,76,0.177,0.155,0.156
125,2025-01-16,MQAC2,77,0.500,0.194,0.195
126,2025-01-16,STA02,78,0.183,0.186,0.188
127,2025-01-16,STDC3,79,0.149,0.152,0.151

In [11]:
df.columns

Index(['Date', 'Sample ID', 'Tube#', 'Rep1 Absorbance 765 nm',
       'Rep2 Absorbance 765 nm', 'Rep3 Absorbance 765 nm'],
      dtype='object')

In [ ]:
for col in df.columns:
    train_test_split(df[])